import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Weather App",
  description: "Generated by create next app",
  icons:{
    icon:['/favicon.ico?v=1'],
    apple:['/apple-touch-icon.png?v=4'],
    shortcut:['/apple-touch-icon.png']

  },
  manifest:'/site.webmanifest',
  creator:"Hamza Chbit",
  authors:[{name:"Hamza Chbit"}],
  publisher:"Hamza chbit",

};





export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
